# Generated by Django 3.0.3 on 2020-04-26 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=200, null=True)),
                ('price', models.FloatField(blank=True, default=None, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
