# Generated by Django 3.0.3 on 2020-04-27 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investments',
            name='date_created',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
