# Generated by Django 3.0.3 on 2020-04-27 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20200427_0700'),
    ]

    operations = [
        migrations.AddField(
            model_name='investments',
            name='current_time',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
