# Generated by Django 3.0.3 on 2020-04-29 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_investments_current_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='investments',
            name='gain_loss',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
